development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: monuments_dev 
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: monuments_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: monuments
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
